import {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Anchor,
  Aperture,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  Award,
  BarChart,
  BarChart2,
  Battery,
  BatteryCharging,
  Bell,
  Bluetooth,
  Bold,
  Book,
  Bookmark,
  Box,
  Briefcase,
  Calendar,
  Camera,
  Cast,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clipboard,
  Clock,
  Cloud,
  CloudDrizzle,
  CloudLightning,
  CloudOff,
  CloudRain,
  CloudSnow,
  Code,
  Codepen,
  Coffee,
  Command,
  Compass,
  Copy,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreditCard,
  Crop,
  Crosshair,
  Database,
  Delete,
  Disc,
  DollarSign,
  Download,
  Droplet,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  FastForward,
  Feather,
  File,
  FileMinus,
  FilePlus,
  FileText,
  Film,
  Filter,
  Flag,
  Folder,
  FolderMinus,
  FolderPlus,
  Gift,
  Github,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Globe,
  Grid,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  ImageIcon,
  Inbox,
  Info,
  Instagram,
  Italic,
  Key,
  Layers,
  Layout,
  LifeBuoy,
  Link,
  Link2,
  List,
  Loader,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Maximize,
  Maximize2,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  MicOff,
  Minimize,
  Minimize2,
  Minus,
  MinusCircle,
  MinusSquare,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Move,
  Music,
  Navigation,
  Navigation2,
  Octagon,
  Package,
  Paperclip,
  Pause,
  PauseCircle,
  Percent,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  PieChart,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  PlusSquare,
  Pocket,
  Power,
  Printer,
  Radio,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Rewind,
  RotateCcw,
  RotateCw,
  Rss,
  Save,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldOff,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sidebar,
  SkipBack,
  SkipForward,
  Slack,
  Slash,
  Sliders,
  Smartphone,
  Smile,
  Speaker,
  Square,
  Star,
  StopCircle,
  Sun,
  Sunrise,
  Sunset,
  Tablet,
  Tag,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  ToggleLeft,
  ToggleRight,
  Trash,
  Trash2,
  Trello,
  TrendingDown,
  TrendingUp,
  Triangle,
  Truck,
  Tv,
  Twitter,
  Type,
  Umbrella,
  Underline,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Video,
  VideoOff,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Watch,
  Wifi,
  WifiOff,
  Wind,
  X,
  XCircle,
  XOctagon,
  XSquare,
  Youtube,
  Zap,
  ZapOff,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

export const iconList = [
  { name: "Activity", component: Activity },
  { name: "AlertCircle", component: AlertCircle },
  { name: "AlertOctagon", component: AlertOctagon },
  { name: "AlertTriangle", component: AlertTriangle },
  { name: "AlignCenter", component: AlignCenter },
  { name: "AlignJustify", component: AlignJustify },
  { name: "AlignLeft", component: AlignLeft },
  { name: "AlignRight", component: AlignRight },
  { name: "Anchor", component: Anchor },
  { name: "Aperture", component: Aperture },
  { name: "Archive", component: Archive },
  { name: "ArrowDown", component: ArrowDown },
  { name: "ArrowLeft", component: ArrowLeft },
  { name: "ArrowRight", component: ArrowRight },
  { name: "ArrowUp", component: ArrowUp },
  { name: "AtSign", component: AtSign },
  { name: "Award", component: Award },
  { name: "BarChart", component: BarChart },
  { name: "BarChart2", component: BarChart2 },
  { name: "Battery", component: Battery },
  { name: "BatteryCharging", component: BatteryCharging },
  { name: "Bell", component: Bell },
  { name: "Bluetooth", component: Bluetooth },
  { name: "Bold", component: Bold },
  { name: "Book", component: Book },
  { name: "Bookmark", component: Bookmark },
  { name: "Box", component: Box },
  { name: "Briefcase", component: Briefcase },
  { name: "Calendar", component: Calendar },
  { name: "Camera", component: Camera },
  { name: "Cast", component: Cast },
  { name: "Check", component: Check },
  { name: "CheckCircle", component: CheckCircle },
  { name: "CheckSquare", component: CheckSquare },
  { name: "ChevronDown", component: ChevronDown },
  { name: "ChevronLeft", component: ChevronLeft },
  { name: "ChevronRight", component: ChevronRight },
  { name: "ChevronUp", component: ChevronUp },
  { name: "Circle", component: Circle },
  { name: "Clipboard", component: Clipboard },
  { name: "Clock", component: Clock },
  { name: "Cloud", component: Cloud },
  { name: "CloudDrizzle", component: CloudDrizzle },
  { name: "CloudLightning", component: CloudLightning },
  { name: "CloudOff", component: CloudOff },
  { name: "CloudRain", component: CloudRain },
  { name: "CloudSnow", component: CloudSnow },
  { name: "Code", component: Code },
  { name: "Codepen", component: Codepen },
  { name: "Coffee", component: Coffee },
  { name: "Command", component: Command },
  { name: "Compass", component: Compass },
  { name: "Copy", component: Copy },
  { name: "CornerDownLeft", component: CornerDownLeft },
  { name: "CornerDownRight", component: CornerDownRight },
  { name: "CornerLeftDown", component: CornerLeftDown },
  { name: "CornerLeftUp", component: CornerLeftUp },
  { name: "CornerRightDown", component: CornerRightDown },
  { name: "CornerRightUp", component: CornerRightUp },
  { name: "CornerUpLeft", component: CornerUpLeft },
  { name: "CornerUpRight", component: CornerUpRight },
  { name: "Cpu", component: Cpu },
  { name: "CreditCard", component: CreditCard },
  { name: "Crop", component: Crop },
  { name: "Crosshair", component: Crosshair },
  { name: "Database", component: Database },
  { name: "Delete", component: Delete },
  { name: "Disc", component: Disc },
  { name: "DollarSign", component: DollarSign },
  { name: "Download", component: Download },
  { name: "Droplet", component: Droplet },
  { name: "Edit", component: Edit },
  { name: "Edit2", component: Edit2 },
  { name: "Edit3", component: Edit3 },
  { name: "ExternalLink", component: ExternalLink },
  { name: "Eye", component: Eye },
  { name: "EyeOff", component: EyeOff },
  { name: "Facebook", component: Facebook },
  { name: "FastForward", component: FastForward },
  { name: "Feather", component: Feather },
  { name: "File", component: File },
  { name: "FileMinus", component: FileMinus },
  { name: "FilePlus", component: FilePlus },
  { name: "FileText", component: FileText },
  { name: "Film", component: Film },
  { name: "Filter", component: Filter },
  { name: "Flag", component: Flag },
  { name: "Folder", component: Folder },
  { name: "FolderMinus", component: FolderMinus },
  { name: "FolderPlus", component: FolderPlus },
  { name: "Gift", component: Gift },
  { name: "Github", component: Github },
  { name: "GitBranch", component: GitBranch },
  { name: "GitCommit", component: GitCommit },
  { name: "GitMerge", component: GitMerge },
  { name: "GitPullRequest", component: GitPullRequest },
  { name: "Globe", component: Globe },
  { name: "Grid", component: Grid },
  { name: "HardDrive", component: HardDrive },
  { name: "Hash", component: Hash },
  { name: "Headphones", component: Headphones },
  { name: "Heart", component: Heart },
  { name: "HelpCircle", component: HelpCircle },
  { name: "Home", component: Home },
  { name: "Image", component: ImageIcon },
  { name: "Inbox", component: Inbox },
  { name: "Info", component: Info },
  { name: "Instagram", component: Instagram },
  { name: "Italic", component: Italic },
  { name: "Key", component: Key },
  { name: "Layers", component: Layers },
  { name: "Layout", component: Layout },
  { name: "LifeBuoy", component: LifeBuoy },
  { name: "Link", component: Link },
  { name: "Link2", component: Link2 },
  { name: "List", component: List },
  { name: "Loader", component: Loader },
  { name: "Lock", component: Lock },
  { name: "LogIn", component: LogIn },
  { name: "LogOut", component: LogOut },
  { name: "Mail", component: Mail },
  { name: "Map", component: Map },
  { name: "MapPin", component: MapPin },
  { name: "Maximize", component: Maximize },
  { name: "Maximize2", component: Maximize2 },
  { name: "Menu", component: Menu },
  { name: "MessageCircle", component: MessageCircle },
  { name: "MessageSquare", component: MessageSquare },
  { name: "Mic", component: Mic },
  { name: "MicOff", component: MicOff },
  { name: "Minimize", component: Minimize },
  { name: "Minimize2", component: Minimize2 },
  { name: "Minus", component: Minus },
  { name: "MinusCircle", component: MinusCircle },
  { name: "MinusSquare", component: MinusSquare },
  { name: "Monitor", component: Monitor },
  { name: "Moon", component: Moon },
  { name: "MoreHorizontal", component: MoreHorizontal },
  { name: "MoreVertical", component: MoreVertical },
  { name: "Move", component: Move },
  { name: "Music", component: Music },
  { name: "Navigation", component: Navigation },
  { name: "Navigation2", component: Navigation2 },
  { name: "Octagon", component: Octagon },
  { name: "Package", component: Package },
  { name: "Paperclip", component: Paperclip },
  { name: "Pause", component: Pause },
  { name: "PauseCircle", component: PauseCircle },
  { name: "Percent", component: Percent },
  { name: "Phone", component: Phone },
  { name: "PhoneCall", component: PhoneCall },
  { name: "PhoneForwarded", component: PhoneForwarded },
  { name: "PhoneIncoming", component: PhoneIncoming },
  { name: "PhoneMissed", component: PhoneMissed },
  { name: "PhoneOff", component: PhoneOff },
  { name: "PhoneOutgoing", component: PhoneOutgoing },
  { name: "PieChart", component: PieChart },
  { name: "Play", component: Play },
  { name: "PlayCircle", component: PlayCircle },
  { name: "Plus", component: Plus },
  { name: "PlusCircle", component: PlusCircle },
  { name: "PlusSquare", component: PlusSquare },
  { name: "Pocket", component: Pocket },
  { name: "Power", component: Power },
  { name: "Printer", component: Printer },
  { name: "Radio", component: Radio },
  { name: "RefreshCcw", component: RefreshCcw },
  { name: "RefreshCw", component: RefreshCw },
  { name: "Repeat", component: Repeat },
  { name: "Rewind", component: Rewind },
  { name: "RotateCcw", component: RotateCcw },
  { name: "RotateCw", component: RotateCw },
  { name: "Rss", component: Rss },
  { name: "Save", component: Save },
  { name: "Scissors", component: Scissors },
  { name: "Search", component: Search },
  { name: "Send", component: Send },
  { name: "Server", component: Server },
  { name: "Settings", component: Settings },
  { name: "Share", component: Share },
  { name: "Share2", component: Share2 },
  { name: "Shield", component: Shield },
  { name: "ShieldOff", component: ShieldOff },
  { name: "ShoppingBag", component: ShoppingBag },
  { name: "ShoppingCart", component: ShoppingCart },
  { name: "Shuffle", component: Shuffle },
  { name: "Sidebar", component: Sidebar },
  { name: "SkipBack", component: SkipBack },
  { name: "SkipForward", component: SkipForward },
  { name: "Slack", component: Slack },
  { name: "Slash", component: Slash },
  { name: "Sliders", component: Sliders },
  { name: "Smartphone", component: Smartphone },
  { name: "Smile", component: Smile },
  { name: "Speaker", component: Speaker },
  { name: "Square", component: Square },
  { name: "Star", component: Star },
  { name: "StopCircle", component: StopCircle },
  { name: "Sun", component: Sun },
  { name: "Sunrise", component: Sunrise },
  { name: "Sunset", component: Sunset },
  { name: "Tablet", component: Tablet },
  { name: "Tag", component: Tag },
  { name: "Target", component: Target },
  { name: "Terminal", component: Terminal },
  { name: "Thermometer", component: Thermometer },
  { name: "ThumbsDown", component: ThumbsDown },
  { name: "ThumbsUp", component: ThumbsUp },
  { name: "ToggleLeft", component: ToggleLeft },
  { name: "ToggleRight", component: ToggleRight },
  { name: "Trash", component: Trash },
  { name: "Trash2", component: Trash2 },
  { name: "Trello", component: Trello },
  { name: "TrendingDown", component: TrendingDown },
  { name: "TrendingUp", component: TrendingUp },
  { name: "Triangle", component: Triangle },
  { name: "Truck", component: Truck },
  { name: "Tv", component: Tv },
  { name: "Twitter", component: Twitter },
  { name: "Type", component: Type },
  { name: "Umbrella", component: Umbrella },
  { name: "Underline", component: Underline },
  { name: "Unlock", component: Unlock },
  { name: "Upload", component: Upload },
  { name: "User", component: User },
  { name: "UserCheck", component: UserCheck },
  { name: "UserMinus", component: UserMinus },
  { name: "UserPlus", component: UserPlus },
  { name: "UserX", component: UserX },
  { name: "Users", component: Users },
  { name: "Video", component: Video },
  { name: "VideoOff", component: VideoOff },
  { name: "Voicemail", component: Voicemail },
  { name: "Volume", component: Volume },
  { name: "Volume1", component: Volume1 },
  { name: "Volume2", component: Volume2 },
  { name: "VolumeX", component: VolumeX },
  { name: "Watch", component: Watch },
  { name: "Wifi", component: Wifi },
  { name: "WifiOff", component: WifiOff },
  { name: "Wind", component: Wind },
  { name: "X", component: X },
  { name: "XCircle", component: XCircle },
  { name: "XOctagon", component: XOctagon },
  { name: "XSquare", component: XSquare },
  { name: "Youtube", component: Youtube },
  { name: "Zap", component: Zap },
  { name: "ZapOff", component: ZapOff },
  { name: "ZoomIn", component: ZoomIn },
  { name: "ZoomOut", component: ZoomOut },
];
